class AddSomeDbIndex < ActiveRecord::Migration
  def up
    add_index :addresses, :location_id
    add_index :addresses, :location_type
    add_index :addresses, :company_id
    add_index :addresses, :customer_id
    add_index :addresses, :supplier_id
    add_index :barcode_settings_suppliers, :supplier_id
    add_index :debit_notes, :supplier_id
    add_index :debit_notes, :warehouse_id
    add_index :debit_notes, :user_id
    add_index :debit_notes, :parent_id
    add_index :deliver_banks, :early_payment_request_id
    add_index :deliver_banks, :user_id
    add_index :details_purchase_orders, :product_id
    add_index :details_purchase_orders, :purchase_order_id
    add_index :early_payment_requests, :purchase_order_id
    add_index :early_payment_requests, :user_id
    add_index :extra_notes, :supplier_id
    add_index :features_roles, :role_id
    add_index :features_roles, :feature_id
    add_index :ldap_settings, :company_id
    add_index :ldap_settings, :user_id
    add_index :level_limits, :warehouse_id
    add_index :notifications, :role_id
    add_index :notifications, :supplier_id
    add_index :payment_details, :payment_id
    add_index :payment_details, :payment_element_id
    add_index :payment_details, :payment_element_type
    add_index :payment_voucher_details, :payment_voucher_id
    add_index :payment_voucher_details, :purchase_order_id
    add_index :payment_vouchers, :supplier_id
    add_index :payment_vouchers, :warehouse_id
    add_index :payment_vouchers, :user_id
    add_index :payments, :supplier_id
    add_index :payments, :warehouse_id
    add_index :purchase_orders, :supplier_id
    add_index :purchase_orders, :user_id
    add_index :purchase_orders, :warehouse_id
    add_index :returned_process_details, :product_id
    add_index :returned_process_details, :returned_process_id
    add_index :returned_processes, :purchase_order_id
    add_index :returned_processes, :user_id
    add_index :roles, :parent_id
    add_index :service_level_histories, :purchase_order_id
    add_index :service_level_histories, :supplier_id
    add_index :suppliers, :parent_id
    add_index :suppliers, :service_level_id
    add_index :suppliers, :group_id
    add_index :suppliers_products, :supplier_id
    add_index :suppliers_products, :product_id
    add_index :type_of_users, :parent_id
    add_index :type_of_users, :company_id
    add_index :user_logs, :user_id
    add_index :user_logs, :log_id
    add_index :user_logs, :log_type
    add_index :users, :company_id
    add_index :users, :supplier_id
    add_index :users, :type_of_user_id
    add_index :users, :warehouse_id
    add_index :users_features, :user_id
    add_index :users_features, :feature_id
    add_index :warehouses, :area_id
    add_index :warehouses, :group_id
    add_index :warehouses_products, :warehouse_id
    add_index :warehouses_products, :product_id
  end

  def down
    remove_index :addresses, :location_id
    remove_index :addresses, :location_type
    remove_index :addresses, :company_id
    remove_index :addresses, :customer_id
    remove_index :addresses, :supplier_id
    remove_index :barcode_settings_suppliers, :supplier_id
    remove_index :debit_notes, :supplier_id
    remove_index :debit_notes, :warehouse_id
    remove_index :debit_notes, :user_id
    remove_index :debit_notes, :parent_id
    remove_index :deliver_banks, :early_payment_request_id
    remove_index :deliver_banks, :user_id
    remove_index :details_purchase_orders, :product_id
    remove_index :details_purchase_orders, :purchase_order_id
    remove_index :early_payment_requests, :purchase_order_id
    remove_index :early_payment_requests, :user_id
    remove_index :extra_notes, :supplier_id
    remove_index :features_roles, :role_id
    remove_index :features_roles, :feature_id
    remove_index :ldap_settings, :company_id
    remove_index :ldap_settings, :user_id
    remove_index :level_limits, :warehouse_id
    remove_index :notifications, :role_id
    remove_index :notifications, :supplier_id
    remove_index :payment_details, :payment_id
    remove_index :payment_details, :payment_element_id
    remove_index :payment_details, :payment_element_type
    remove_index :payment_voucher_details, :payment_voucher_id
    remove_index :payment_voucher_details, :purchase_order_id
    remove_index :payment_vouchers, :supplier_id
    remove_index :payment_vouchers, :warehouse_id
    remove_index :payment_vouchers, :user_id
    remove_index :payments, :supplier_id
    remove_index :payments, :warehouse_id
    remove_index :purchase_orders, :supplier_id
    remove_index :purchase_orders, :user_id
    remove_index :purchase_orders, :warehouse_id
    remove_index :returned_process_details, :product_id
    remove_index :returned_process_details, :returned_process_id
    remove_index :returned_processes, :purchase_order_id
    remove_index :returned_processes, :user_id
    remove_index :roles, :parent_id
    remove_index :service_level_histories, :purchase_order_id
    remove_index :service_level_histories, :supplier_id
    remove_index :suppliers, :parent_id
    remove_index :suppliers, :service_level_id
    remove_index :suppliers, :group_id
    remove_index :suppliers_products, :supplier_id
    remove_index :suppliers_products, :product_id
    remove_index :type_of_users, :parent_id
    remove_index :type_of_users, :company_id
    remove_index :user_logs, :user_id
    remove_index :user_logs, :log_id
    remove_index :user_logs, :log_type
    remove_index :users, :company_id
    remove_index :users, :supplier_id
    remove_index :users, :type_of_user_id
    remove_index :users, :warehouse_id
    remove_index :users_features, :user_id
    remove_index :users_features, :feature_id
    remove_index :warehouses, :area_id
    remove_index :warehouses, :group_id
    remove_index :warehouses_products, :warehouse_id
    remove_index :warehouses_products, :product_id
  end
end
